### ISSUE TITLE
Cannot read property 'command' of undefined

### ISSUE THREAD

**Issue by nurtext** [Flynsarmy/atom-open-terminal-here#16]
**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.4
**Thrown From**: [open-terminal-here](https://github.com/Flynsarmy/atom-open-terminal-here) package, v0.5.0
### Stack Trace

Failed to activate the open-terminal-here package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/cedric/.atom/packages/open-terminal-here/lib/open-terminal-here.coffee:15:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -0:28.7.0 core:cancel (input.hidden-input)
  3x -0:28.4.0 core:move-down (input.hidden-input)
  2x -0:27.7.0 core:move-right (input.hidden-input)
     -0:27.2.0 core:select-right (input.hidden-input)
     -0:26.6.0 color-picker:open (input.hidden-input)
     -0:25.5.0 editor:consolidate-selections (input.hidden-input)
     -0:25.5.0 core:cancel (input.hidden-input)
  9x -0:25 core:move-down (input.hidden-input)
  6x -0:23.8.0 core:move-left (input.hidden-input)
     -0:22.9.0 core:select-left (input.hidden-input)
     -0:22.2.0 color-picker:open (input.hidden-input)
     -0:19.6.0 editor:consolidate-selections (input.hidden-input)
     -0:19.6.0 core:cancel (input.hidden-input)
     -0:18.9.0 color-picker:open (input.hidden-input)
     -0:17.5.0 editor:consolidate-selections (input.hidden-input)
     -0:17.5.0 core:cancel (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "followSymlinks": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "feedback",
      "archive-view",
      "open-on-github",
      "package-generator",
      "release-notes",
      "styleguide",
      "autosave",
      "deprecation-cop",
      "language-jade",
      "language-swift",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "specials-board"
    ],
    "audioBeep": false
  },
  "open-terminal-here": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.7
emmet, v2.3.10
file-icons, v1.5.7
language-volt, v0.2.2
linter, v0.12.7
linter-csslint, v0.0.13
linter-jshint, v0.1.6
linter-php, v0.0.15
minimap, v4.10.0
open-terminal-here, v0.5.0
specials-board, v0.6.1
symbols-tree-view, v0.9.3
tabs-to-spaces, v0.11.0
tool-bar, v0.1.8
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by doginthehat** [comment]
Same here

**Atom Version**: 0.211.0
**System**: Mac OS X 10.9.5
**Thrown From**: [open-terminal-here](https://github.com/Flynsarmy/atom-open-terminal-here) package, v0.5.0

### Installed Packages

``` coffee
# User
color-picker, v2.0.7
language-blade, v0.14.0
linter, v0.12.7
linter-php, v0.0.15
open-terminal-here, v0.5.0
php-twig, v4.0.0
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by danielandrews** [comment]
I'm seeing a similar issue.

**Comment by blueimp** [comment]
I think this was fixed with my pull request:
https://github.com/Flynsarmy/atom-open-terminal-here/pull/13

It has been merged, but @Flynsarmy didn't release the new version yet.

**Comment by doginthehat** [comment]
Doesn't seem like the update has been pushed live, it's still throwing the same error. 

open-terminal-here package: 0.5.0 still
Atom Version 1.0.2 now.

**Comment by Flynsarmy** [comment]
My plugin isn't even in the plugins repo on the atom website anymore - I no longer use Atom editor so someone please fork and publish a new and improved version of my plugin.

**Comment by blueimp** [comment]
Done:
https://atom.io/packages/open-terminal-here

Thanks for your work, @Flynsarmy !

**Comment by doginthehat** [comment]
Thanks @blueimp – just installed it, worked a treat.

Thanks @Flynsarmy for the initial work on this.
