### ISSUE TITLE
Stopped working in v0.129.0

### ISSUE THREAD

**Issue by gilbitron** [Flynsarmy/atom-open-terminal-here#4]
This plugin has worked fine for me for ages. All of a sudden recently it just doesn't work (clicking the context menu item does nothing).

Open Terminal Here v0.2.0
Atom v0.129.0
iTerm2 v1.0.0.20140629

**Comment by rafa2000** [comment]
Same here.

Open Terminal Here v0.2.0
Atom v0.182.0
Terminal.app 2.5.1

**Comment by Flynsarmy** [comment]
Has this been fixed in the latest version?

**Comment by doginthehat** [comment]
No, still not.

I'm on Atom 0.182.0 (latest)

Open Terminal Here is still v0.2.0 (no update available)

**Comment by doginthehat** [comment]
Works now.

Atom 0.190.0 & Open Terminal Here 0.5.0
